# -*- coding: utf-8 -*-
"""9.Comparison operator .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lVkAwj-Xx4556mUpaa19LrzTdT97NKdu
"""

#used to compare to values or expression these return values true or false

#equal symbol ==
a=2
b=2
result = (a == b)
print(result)#true

c =1
d=0
print( c==d)#false

#inequality  symbol !=
a=2
b=23
print(a!=b)  #true


c=3
d=3
print(c!=d)#false

#greater than >

a=2
b=40
print(a>b) #false
print(b>a)#true

#less than  symbol <

a=40
b=30
print(a<b) #false
print(b<a) #true