# -*- coding: utf-8 -*-
"""Agg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aqvYvx5fMLmsSro5FyrftkY5FP6QkrGh
"""

import pandas as pd

# Creating a sample DataFrame
data = {
    'Name': ['John', 'Alice', 'Bob', 'Mike', 'Sarah'],
    'Age': [25, 30, 22, 35, 28],
    'Salary': [50000, 60000, 45000, 70000, 65000],
    'Department': ['Engineering', 'Medicine', 'Arts', 'Law', 'Engineering']
}

df = pd.DataFrame(data)

# Display the DataFrame
print("DataFrame:")
print(df)

# Indexing a single column
print("\nSingle column (Name):")
print(df['Name'])

# Slicing rows and selecting specific columns
print("\nSliced rows and columns (Rows 1 to 3, 'Name' and 'Salary'):")
print(df.loc[1:3, ['Name', 'Salary']])

# Sorting by 'Salary' in descending order
print("\nSorted by Salary (Descending):")
print(df.sort_values(by='Salary', ascending=False))

# Aggregating the 'Salary' column
print("\nAggregating Salary (mean, min, max, sum):")
print(df['Salary'].agg(['mean', 'min', 'max', 'sum']))

# Grouping by 'Department' and calculating the mean of 'Salary'
print("\nMean Salary by Department:")
print(df.groupby('Department')['Salary'].mean())

