# -*- coding: utf-8 -*-
"""ConditionalStatements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Cv5Aer5e8kgjFcJVucqzmgI2MDk60EG
"""

# if statement
#
x=-1
if x>0:
   print("x is positive")

y=10
if y<11:
  print("Y is 10")


"""< less  than
> greather than
"""

#elif statement
x = 101

if x > 10:
    print("Greater than 10")
elif x < 10:
    print("Less than 10")
else:
    print("Equal to 10")

#if else  statement
x = 10

if x > 10:
    print("Greater than 10")
else:
    print("Equal to 10")