# -*- coding: utf-8 -*-
"""Lists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-vcoM-ctTjbMfL7h-XfVr2w4_2HkKw7

list is zero index based
"""

numbers=[1,2,3,4,5,6]
print(numbers)
print((len(numbers)))

print(numbers[1]) #accessing the list
print(numbers[-2])#accessing the list

#Slicing
my=numbers[1:4] #from 1 elements to 4 element
print(my)

my=numbers[:4]
print(my)

my=numbers[1:]
print(my)

numbers[3]=30 #updating a values by there index
print(numbers)

numbers.remove(30)
print(numbers)

strings=["apple","students","laptop","samsung"]
print(strings)
print(len(strings))

print(strings[3]) #accessing the list
print(strings[-2])#accessing the list

#Slicing
words=strings[1:4] #from 1 elements to 4 element
print(words)

words=strings[:2]
print(words)

strings[2]="Smartwatch"
print(strings)

strings.remove("Smartwatch")
print(strings)

mixed=["apple",2,3.18,True]
print(mixed)
print(len(mixed))