# -*- coding: utf-8 -*-
"""Looping statements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dPdtUss8KkKhbTgJNSo16_zdMhoE8pIG
"""

#for loop
for loop in range(3):
  print("loop")

for i in range(1):
  print(i)

#Range(Start and Stop)
for y in range(2,10): #Stating and stoping postions
  print(y)

#Range (Start stop step)
for z in range(17,24,3): #3 skips 2 values
  print(z)

word="Python"
for char in word:
  print(char)
  print(char.split())#like asn object

#while loop
password=""
while len(password) <8:
  password=input("Enter the password");


choice = None  # Initialize choice variable

while choice != "q":  # Continue the loop until the user enters "q"
    print("Option 1")
    print("Option 2")
    print("Option 3")

    choice = input("Enter your choice (or 'q' to quit): ")  # Get user input

