# -*- coding: utf-8 -*-
"""Tuples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uRKmnyAJjC_W5NO-YDr8e2WzcIeGYNjm
"""

#order and immtable dsa
tuples=(1,2,3,4,5)
print(tuples)
print(len(tuples))

new=tuples + (3,)
print(new)

print(type(tuples))

tuples=("hi","hello")
print(tuples)
print(len(tuples))